name: belfa
description: "A new Flutter project."
publish_to: "https://github.com/Hadi719/Belfa/releases"
platforms:
  android:

version: 0.0.1+2

# Created with flutter 3.24.1 (Dart 3.5.1) => working: 3.24.4
environment:
  sdk: ^3.5.3

isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  logging: ^1.3.0
  path_provider: ^2.1.4
  get: ^4.6.6
  isar: *isar_version
  isar_flutter_libs: *isar_version
  file_picker: ^8.1.3
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: *isar_version

flutter:
  uses-material-design: true
